# Generated by Django 6.0.2 on 2026-02-26 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Household',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('household_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'household',
            },
        ),
        migrations.CreateModel(
            name='WeatherRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_date', models.DateField(unique=True)),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('wind_speed', models.FloatField()),
                ('weather_condition', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'weather_record',
            },
        ),
        migrations.CreateModel(
            name='GasRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_month', models.CharField(max_length=7)),
                ('consumption_gj', models.FloatField()),
                ('amount', models.FloatField()),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gas_records', to='kg.household')),
            ],
            options={
                'db_table': 'gas_record',
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=50, unique=True)),
                ('device_name', models.CharField(max_length=100)),
                ('device_type', models.CharField(max_length=50)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='kg.household')),
            ],
            options={
                'db_table': 'device',
            },
        ),
        migrations.CreateModel(
            name='ElectricityRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_date', models.DateField()),
                ('record_hour', models.IntegerField(default=0)),
                ('energy_kwh', models.FloatField(default=0)),
                ('peak_power', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='kg.device')),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='electricity_records', to='kg.household')),
            ],
            options={
                'db_table': 'electricity_record',
                'indexes': [models.Index(fields=['record_date', 'device'], name='electricity_record__99e961_idx')],
            },
        ),
    ]
