# Generated by Django 6.0.2 on 2026-05-11 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kg', '0001_v2_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptionDict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('item_key', models.CharField(max_length=50)),
                ('item_value', models.CharField(max_length=200)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_active', models.SmallIntegerField(default=1)),
            ],
            options={
                'db_table': 'option_dict',
                'ordering': ['category', 'sort_order', 'item_key'],
                'unique_together': {('category', 'item_key')},
            },
        ),
    ]
