# Generated by Django 6.0.2 on 2026-05-11 04:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kg', '0002_add_option_dict'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice_type', models.SmallIntegerField(default=1)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('is_read', models.SmallIntegerField(default=0)),
                ('is_pinned', models.SmallIntegerField(default=0)),
                ('bill_month', models.CharField(max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notices', to='kg.bill')),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notices', to='kg.household')),
            ],
            options={
                'db_table': 'notice',
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
    ]
