"""
Django settings for power_profile project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-change-this-to-random-string-in-production'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'kg',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'power_profile.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'power_profile.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'electric_user_profile',
        'USER': 'root',
        'PASSWORD': 'your_mysql_password',
        'HOST': 'localhost',
        'PORT': '3306',
        'OPTIONS': {
            'charset': 'utf8mb4',
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# Neo4j Configuration
# 如果存在settings.local.py，从中读取配置，覆盖默认配置
local_settings_path = BASE_DIR / 'power_profile' / 'settings.local.py'

if local_settings_path.exists():
    import importlib.util
    spec = importlib.util.spec_from_file_location("local_settings", local_settings_path)
    local_settings = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(local_settings)

    # 使用本地配置覆盖
    NEO4J_CONFIG = getattr(local_settings, 'NEO4J_CONFIG', {
        'URI': 'bolt://localhost:7687',
        'AUTH': ('neo4j', 'password'),
        'DATABASE': 'neo4j',
    })

    # 覆盖 SECRET_KEY（如果本地配置中有）
    if hasattr(local_settings, 'SECRET_KEY'):
        SECRET_KEY = local_settings.SECRET_KEY

    # 覆盖 DATABASES（如果本地配置中有）
    if hasattr(local_settings, 'DATABASES'):
        DATABASES = local_settings.DATABASES
else:
    NEO4J_CONFIG = {
        'URI': 'bolt://localhost:7687',
        'AUTH': ('neo4j', 'your_neo4j_password'),
        'DATABASE': 'neo4j',
    }

# Data directory
# 使用REFIT数据集
DATA_DIR = BASE_DIR / 'kg_refit_data'

# 可选：原始数据目录
ORIGINAL_DATA_DIR = BASE_DIR / 'processed_data'

# JWT Configuration
JWT_SECRET = 'your_jwt_secret_change_in_production'
JWT_ALGORITHM = 'HS256'
JWT_EXPIRATION_HOURS = 168  # 7 days
